name: Semgrep

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '23 4 * * 1'

jobs:
  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/php
            p/owasp-top-ten
          generateSarif: "1"

      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
